<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Jayarees-MacBook-Pro.local" ignored="0" name="chrome" tests="3" failures="1" timestamp="24 Aug 2020 12:45:21 GMT" time="160.308" errors="0">
  <testcase name="i_am_a_new_user" time="13.816" classname="Stepdef.Successful_voucher_with_top_up"/>
  <testcase name="i_reg_and_add_a_voucher_with_top_up" time="146.33" classname="Stepdef.Successful_voucher_with_top_up">
    <failure type="java.lang.AssertionError" message="expected [13.00s] but found [15.00]">
      <![CDATA[java.lang.AssertionError: expected [13.00s] but found [15.00]
at Stepdef.Successful_voucher_with_top_up.i_reg_and_add_a_voucher_with_top_up(Successful_voucher_with_top_up.java:71)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- i_reg_and_add_a_voucher_with_top_up -->
  <testcase name="i_get_a_wallet_with_top_up_amount_plus_the_voucher_amount" time="0.136" classname="Stepdef.Successful_voucher_with_top_up"/>
</testsuite> <!-- chrome -->
